In [1]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv('sentiment_crime_matches.csv')
df.head(10)

,PSOS_MMW_Name,COUNCIL NAME,week_start,week_end,WARD CODE,Population_Census_2022-03-20,Area,"Alcohol offences, travelling to and from sporting event",Breach of football banning order,Breach of the peace,...,TOTAL DETECTED CRIME_lag3,normalized_crime_delta_lag4,normalized_crime_delta_lag5,normalized_crime_delta_lag6,TOTAL DETECTED CRIME_lag4,TOTAL DETECTED CRIME_lag5,TOTAL DETECTED CRIME_lag6,weighted_sentiment_lag4,weighted_sentiment_lag5,weighted_sentiment_lag6
0,Abbey,Dumfries and Galloway,2019-06-03,2019-06-09,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0.00,0.000000,0.000000,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.000000
1,Abbey,Dumfries and Galloway,2019-06-10,2019-06-16,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0.00,0.000000,0.000000,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.000000
2,Abbey,Dumfries and Galloway,2019-06-17,2019-06-23,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0.00,0.000000,0.000000,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.000000
3,Abbey,Dumfries and Galloway,2019-06-24,2019-06-30,S13002884,10176.0,204.87,0.0,0.0,0.00,...,11.06,0.000000,0.000000,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.000000
4,Abbey,Dumfries and Galloway,2019-07-01,2019-07-07,S13002884,10176.0,204.87,0.0,0.0,0.91,...,11.06,0.000000,0.000000,0.000000,11.06,0.00,0.00,-1.340977,0.000000,0.000000
5,Abbey,Dumfries and Galloway,2019-07-08,2019-07-14,S13002884,10176.0,204.87,0.0,0.0,0.91,...,11.06,0.000000,0.000000,0.000000,11.06,11.06,0.00,-1.340977,-1.340977,0.000000
6,Abbey,Dumfries and Galloway,2019-07-15,2019-07-21,S13002884,10176.0,204.87,0.0,0.0,0.91,...,3.00,0.000000,0.000000,0.000000,11.06,11.06,11.06,-1.340977,-1.340977,-1.340977
7,Abbey,Dumfries and Galloway,2019-07-22,2019-07-28,S13002884,10176.0,204.87,0.0,0.0,0.91,...,11.06,-3.969201,0.000000,0.000000,3.00,11.06,11.06,-1.053414,-1.340977,-1.340977
8,Abbey,Dumfries and Galloway,2019-07-29,2019-08-04,S13002884,10176.0,204.87,0.0,0.0,0.00,...,11.06,3.969201,-3.969201,0.000000,11.06,3.00,11.06,-1.381413,-1.053414,-1.340977
9,Abbey,Dumfries and Galloway,2019-08-05,2019-08-11,S13002884,10176.0,204.87,0.0,0.0,0.22,...,11.06,0.000000,3.969201,-3.969201,11.06,11.06,3.00,-1.381413,-1.381413,-1.053414

In [4]:
df.shape

(111428, 66)

In [6]:
df.columns.unique()

Index(['PSOS_MMW_Name', 'COUNCIL NAME', 'week_start', 'week_end', 'WARD CODE',
       'Population_Census_2022-03-20', 'Area',
       'Alcohol offences, travelling to and from sporting event',
       'Breach of football banning order', 'Breach of the peace',
       'Carrying of Knives etc S Act 1993',
       'Drunk in or attempting to enter designated sports ground',
       'Mobbing and rioting',
       'Offensive behaviour at football (OBaFaTBSA 2012)',
       'Permitting riotous behaviour in licensed premises',
       'Possession of an offensive weapon',
       'Possession of offensive weapon used in other criminal activity',
       'Public mischief - including wasting police time',
       'Racially aggravated conduct', 'Racially aggravated harassment',
       'Serious Assault', 'Sports grounds offences possessing alcohol etc',
       'Stirring up hatred: Racial', 'Threatening or abusive behaviour',
       'TOTAL DETECTED CRIME', 'weighted_sentiment', 'Aberdeen', 'Celtic',
       'Dundee', 'Dundee United', 'Hamilton Acad.', 'Hearts', 'Hibernian',
       'Inverness CT', 'Kilmarnock', 'Livingston', 'Motherwell',
       'Partick Thistle', 'Rangers', 'Ross County', 'St Johnstone',
       'St Mirren', 'CALENDAR MONTH', 'CALENDAR YEAR', 'latitude', 'longitude',
       'normalized_crime_delta', 'weighted_sentiment_lag1',
       'weighted_sentiment_lag2', 'weighted_sentiment_lag3', 'hotspot',
       'normalized_crime_delta_lag1', 'normalized_crime_delta_lag2',
       'normalized_crime_delta_lag3', 'TOTAL DETECTED CRIME_lag1',
       'TOTAL DETECTED CRIME_lag2', 'TOTAL DETECTED CRIME_lag3',
       'normalized_crime_delta_lag4', 'normalized_crime_delta_lag5',
       'normalized_crime_delta_lag6', 'TOTAL DETECTED CRIME_lag4',
       'TOTAL DETECTED CRIME_lag5', 'TOTAL DETECTED CRIME_lag6',
       'weighted_sentiment_lag4', 'weighted_sentiment_lag5',
       'weighted_sentiment_lag6'],
      dtype='object')

In [4]:
df['WARD CODE'].unique()

array(['S13002884', 'S13002503', 'S13002674', 'S13002719', 'S13002718',
       'S13002722', 'S13002486', 'S13002583', 'S13002746', 'S13002608',
       'S13002976', 'S13002544', 'S13002543', 'S13002542', 'S13002553',
       'S13002514', 'S13002872', 'S13002708', 'S13002828', 'S13002791',
       'S13002782', 'S13002781', 'S13002783', 'S13002682', 'S13002660',
       'S13002559', 'S13002504', 'S13002489', 'S13002813', 'S13002600',
       'S13002914', 'S13002827', 'S13002563', 'S13002564', 'S13002601',
       'S13002725', 'S13002904', 'S13002833', 'S13002759', 'S13002671',
       'S13002740', 'S13002801', 'S13002609', 'S13002613', 'S13002691',
       'S13002802', 'S13002868', 'S13002477', 'S13002821', 'S13002640',
       'S13002698', 'S13002627', 'S13002649', 'S13002800', 'S13002799',
       'S13002656', 'S13002673', 'S13002970', 'S13002871', 'S13002738',
       'S13002612', 'S13002883', 'S13002492', 'S13002929', 'S13002529',
       'S13002531', 'S13002528', 'S13002530', 'S13002527', 'S13002917',
       'S13002818', 'S13002819', 'S13002789', 'S13002788', 'S13002790',
       'S13002787', 'S13003048', 'S13002721', 'S13002720', 'S13002548',
       'S13002590', 'S13002588', 'S13002521', 'S13002625', 'S13002596',
       'S13002668', 'S13002679', 'S13003045', 'S13002713', 'S13002714',
       'S13002560', 'S13002638', 'S13002692', 'S13002709', 'S13002882',
       'S13002988', 'S13002611', 'S13002670', 'S13002561', 'S13002585',
       'S13002654', 'S13002816', 'S13002576', 'S13002809', 'S13002620',
       'S13002619', 'S13002621', 'S13002522', 'S13002476', 'S13002767',
       'S13002658', 'S13002551', 'S13002500', 'S13002794', 'S13002793',
       'S13002796', 'S13002792', 'S13002795', 'S13002824', 'S13002736',
       'S13002637', 'S13002666', 'S13002999', 'S13002701', 'S13002702',
       'S13002497', 'S13002760', 'S13002614', 'S13002615', 'S13002825',
       'S13002699', 'S13002510', 'S13002703', 'S13002586', 'S13002808',
       'S13002723', 'S13002591', 'S13002491', 'S13002683', 'S13002763',
       'S13002653', 'S13002483', 'S13002579', 'S13002786', 'S13003047',
       'S13002633', 'S13002632', 'S13002631', 'S13002645', 'S13002610',
       'S13002643', 'S13002575', 'S13002803', 'S13002805', 'S13002804',
       'S13002770', 'S13002771', 'S13002844', 'S13002700', 'S13002525',
       'S13002526', 'S13002741', 'S13002651', 'S13002480', 'S13002758',
       'S13002634', 'S13002502', 'S13003013', 'S13002684', 'S13002685',
       'S13002686', 'S13002687', 'S13002689', 'S13002688', 'S13002623',
       'S13002587', 'S13002676', 'S13002678', 'S13003004', 'S13002681',
       'S13002675', 'S13002499', 'S13002705', 'S13003041', 'S13002558',
       'S13002704', 'S13002523', 'S13002769', 'S13003083', 'S13003082',
       'S13002697', 'S13002768', 'S13002710', 'S13002556', 'S13002554',
       'S13002557', 'S13002555', 'S13002817', 'S13002712', 'S13002706',
       'S13002488', 'S13002478', 'S13002745', 'S13002517', 'S13002629',
       'S13002630', 'S13002628', 'S13002907', 'S13002732', 'S13002733',
       'S13002508', 'S13002784', 'S13002647', 'S13002806', 'S13002765',
       'S13002595', 'S13002594', 'S13002568', 'S13002777', 'S13002778',
       'S13002815', 'S13002639', 'S13002598', 'S13002820', 'S13002641',
       'S13002822', 'S13002823', 'S13002607', 'S13002540', 'S13002546',
       'S13002952', 'S13002814', 'S13002524', 'S13002616', 'S13002484',
       'S13002549', 'S13002981', 'S13002785', 'S13002507', 'S13002518',
       'S13002766', 'S13002496', 'S13002881', 'S13002539', 'S13002694',
       'S13002695', 'S13002693', 'S13002482', 'S13002562', 'S13002829',
       'S13002874', 'S13002928', 'S13002726', 'S13002728', 'S13002729',
       'S13002727', 'S13002730', 'S13002908', 'S13002602', 'S13003007',
       'S13002642', 'S13002915', 'S13002918', 'S13002541', 'S13002574',
       'S13002711', 'S13002987', 'S13002830', 'S13002737', 'S13002772',
       'S13002505', 'S13002538', 'S13002662', 'S13002479', 'S13002520',
       'S13002519', 'S13003079', 'S13003077', 'S13002753', 'S13003080',
       'S13002755', 'S13002989', 'S13002690', 'S13002584', 'S13002749',
       'S13002748', 'S13002747', 'S13002493', 'S13002494', 'S13002646',
       'S13002599', 'S13002572', 'S13002780', 'S13003075', 'S13002751',
       'S13002622', 'S13002798', 'S13002797', 'S13002707', 'S13002764',
       'S13002603', 'S13002604', 'S13002775', 'S13002773', 'S13002776',
       'S13002774', 'S13002659', 'S13002589', 'S13002516', 'S13002648',
       'S13002597', 'S13002696', 'S13002983', 'S13002962', 'S13002605',
       'S13002606', 'S13003046', 'S13002812', 'S13003118', 'S13002811',
       'S13002506', 'S13002880', 'S13002744', 'S13002743', 'S13002545',
       'S13002739', 'S13002742', 'S13002734', 'S13002669', 'S13002635',
       'S13002552', 'S13002724', 'S13002991', 'S13002481', 'S13002487',
       'S13002910', 'S13003087', 'S13002807', 'S13002490', 'S13002495',
       'S13002762', 'S13002761', 'S13002617', 'S13002978', 'S13002547',
       'S13002618', 'S13002498', 'S13002735', 'S13002667', 'S13002501',
       'S13002826', 'S13002992', 'S13002731'], dtype=object)

In [7]:
df['WARD CODE'].nunique()

353

In [8]:
df = df.rename(columns={'PSOS_MMW_Name': 'source_location'})
df.head()

,source_location,COUNCIL NAME,week_start,week_end,WARD CODE,Population_Census_2022-03-20,Area,"Alcohol offences, travelling to and from sporting event",Breach of football banning order,Breach of the peace,...,TOTAL DETECTED CRIME_lag3,normalized_crime_delta_lag4,normalized_crime_delta_lag5,normalized_crime_delta_lag6,TOTAL DETECTED CRIME_lag4,TOTAL DETECTED CRIME_lag5,TOTAL DETECTED CRIME_lag6,weighted_sentiment_lag4,weighted_sentiment_lag5,weighted_sentiment_lag6
0,Abbey,Dumfries and Galloway,2019-06-03,2019-06-09,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0
1,Abbey,Dumfries and Galloway,2019-06-10,2019-06-16,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0
2,Abbey,Dumfries and Galloway,2019-06-17,2019-06-23,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0
3,Abbey,Dumfries and Galloway,2019-06-24,2019-06-30,S13002884,10176.0,204.87,0.0,0.0,0.00,...,11.06,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0
4,Abbey,Dumfries and Galloway,2019-07-01,2019-07-07,S13002884,10176.0,204.87,0.0,0.0,0.91,...,11.06,0.0,0.0,0.0,11.06,0.0,0.0,-1.340977,0.0,0.0

In [9]:
df = df.rename(columns={
    'CALENDAR YEAR': 'year',
    'CALENDAR MONTH': 'month',
    'TOTAL DETECTED CRIME': 'DETECTED CRIME'
})
df.head()

,source_location,COUNCIL NAME,week_start,week_end,WARD CODE,Population_Census_2022-03-20,Area,"Alcohol offences, travelling to and from sporting event",Breach of football banning order,Breach of the peace,...,TOTAL DETECTED CRIME_lag3,normalized_crime_delta_lag4,normalized_crime_delta_lag5,normalized_crime_delta_lag6,TOTAL DETECTED CRIME_lag4,TOTAL DETECTED CRIME_lag5,TOTAL DETECTED CRIME_lag6,weighted_sentiment_lag4,weighted_sentiment_lag5,weighted_sentiment_lag6
0,Abbey,Dumfries and Galloway,2019-06-03,2019-06-09,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0
1,Abbey,Dumfries and Galloway,2019-06-10,2019-06-16,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0
2,Abbey,Dumfries and Galloway,2019-06-17,2019-06-23,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0
3,Abbey,Dumfries and Galloway,2019-06-24,2019-06-30,S13002884,10176.0,204.87,0.0,0.0,0.00,...,11.06,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0
4,Abbey,Dumfries and Galloway,2019-07-01,2019-07-07,S13002884,10176.0,204.87,0.0,0.0,0.91,...,11.06,0.0,0.0,0.0,11.06,0.0,0.0,-1.340977,0.0,0.0

In [10]:
df = df.drop(columns=[
    'weighted_sentiment_lag1',
    'weighted_sentiment_lag2',
    'weighted_sentiment_lag3',
    'hotspot',
    'normalized_crime_delta_lag1',
    'normalized_crime_delta_lag2',
    'normalized_crime_delta_lag3',
    'TOTAL DETECTED CRIME_lag1',
    'TOTAL DETECTED CRIME_lag2',
    'TOTAL DETECTED CRIME_lag3',
    'normalized_crime_delta_lag4',
    'normalized_crime_delta_lag5',
    'normalized_crime_delta_lag6',
    'TOTAL DETECTED CRIME_lag4',
    'TOTAL DETECTED CRIME_lag5',
    'TOTAL DETECTED CRIME_lag6',
    'weighted_sentiment_lag4',
    'weighted_sentiment_lag5',
    'weighted_sentiment_lag6'
])

In [11]:
df.head()

,source_location,COUNCIL NAME,week_start,week_end,WARD CODE,Population_Census_2022-03-20,Area,"Alcohol offences, travelling to and from sporting event",Breach of football banning order,Breach of the peace,...,Partick Thistle,Rangers,Ross County,St Johnstone,St Mirren,month,year,latitude,longitude,normalized_crime_delta
0,Abbey,Dumfries and Galloway,2019-06-03,2019-06-09,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0,0,0,0,0,6,2019,54.962841,-3.64425,0.000000
1,Abbey,Dumfries and Galloway,2019-06-10,2019-06-16,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0,0,0,0,0,6,2019,54.962841,-3.64425,0.000000
2,Abbey,Dumfries and Galloway,2019-06-17,2019-06-23,S13002884,10176.0,204.87,0.0,0.0,0.89,...,0,0,0,0,0,6,2019,54.962841,-3.64425,0.000000
3,Abbey,Dumfries and Galloway,2019-06-24,2019-06-30,S13002884,10176.0,204.87,0.0,0.0,0.00,...,0,0,0,0,0,6,2019,54.962841,-3.64425,-3.969201
4,Abbey,Dumfries and Galloway,2019-07-01,2019-07-07,S13002884,10176.0,204.87,0.0,0.0,0.91,...,0,0,0,0,0,7,2019,54.962841,-3.64425,3.969201

In [12]:
df.to_json('ward_crimes.json', orient='records')

In [13]:
percentiles = np.arange(0, 102, 2)
detected_crime_percentiles = np.percentile(df['DETECTED CRIME'], percentiles)
for p, v in zip(percentiles, detected_crime_percentiles):
    print(f"{p}%: {v}")

0%: 0.0
2%: 1.0
4%: 2.0
6%: 4.0
8%: 5.0
10%: 7.0
12%: 9.0
14%: 10.86
16%: 10.91
18%: 10.93
20%: 10.95
22%: 10.97
24%: 10.98
26%: 11.0
28%: 11.0
30%: 11.02
32%: 11.03
34%: 11.04
36%: 11.05
38%: 11.06
40%: 11.06
42%: 11.07
44%: 11.08
46%: 11.09
48%: 11.1
50%: 11.11
52%: 11.11
54%: 11.12
56%: 11.13
58%: 11.14
60%: 11.15
62%: 11.16
64%: 11.17
66%: 11.18
68%: 11.2
70%: 11.21
72%: 11.22
74%: 11.23
76%: 11.25
78%: 11.26
80%: 11.28
82%: 11.29
84%: 11.31
86%: 11.33
88%: 11.35
90%: 11.38
92%: 12.0
94%: 13.0
96%: 17.0
98%: 24.0
100%: 248.0

In [14]:
detected_crime_summary = {
    'count': df['DETECTED CRIME'].count(),
    'mean': df['DETECTED CRIME'].mean(),
    'std': df['DETECTED CRIME'].std(),
    'min': df['DETECTED CRIME'].min(),
    '25%': df['DETECTED CRIME'].quantile(0.25),
    '50% (median)': df['DETECTED CRIME'].median(),
    '75%': df['DETECTED CRIME'].quantile(0.75),
    'max': df['DETECTED CRIME'].max(),
    'sum': df['DETECTED CRIME'].sum()
}
detected_crime_summary

{'count': 111428,
 'mean': 11.03135378899379,
 'std': 5.832672588468418,
 'min': 0.0,
 '25%': 10.99,
 '50% (median)': 11.11,
 '75%': 11.24,
 'max': 248.0,
 'sum': 1229201.6900000002}

Maximum DETECTED CRIME: 248.0
Minimum DETECTED CRIME: 0.0

SyntaxError: positional argument follows keyword argument (3597683900.py, line 1)

In [5]:
city_mapping = {
    'Aberdeen': 'Aberdeen City',
    'Glasgow': 'Glasgow City',
    'Edinburgh': 'City of Edinburgh',
    'Orkney': 'Orkney Islands',
    'Shetland': 'Shetland Islands',
    'Dundee': 'Dundee City',
    'Western Isles - Eilean Siar': 'Na h-Eileanan Siar'
}

df['source_location'] = df['source_location'].replace(city_mapping)

df['source_location'].unique()

array(['Aberdeen City', 'Aberdeenshire', 'Angus', 'Argyll and Bute',
       'Clackmannanshire', 'Dumfries and Galloway', 'Dundee City',
       'East Ayrshire', 'East Dunbartonshire', 'East Lothian',
       'East Renfrewshire', 'City of Edinburgh', 'Falkirk', 'Fife',
       'Glasgow City', 'Highland', 'Inverclyde', 'Midlothian', 'Moray',
       'North Ayrshire', 'North Lanarkshire', 'Orkney Islands',
       'Perth and Kinross', 'Renfrewshire', 'Scottish Borders',
       'Shetland Islands', 'South Ayrshire', 'South Lanarkshire',
       'Stirling', 'West Dunbartonshire', 'West Lothian',
       'Na h-Eileanan Siar'], dtype=object)

In [5]:
df.head()

,year,month,source_location,DETECTED CRIME,negative,neutral,positive,total,neg_ratio
0,2019,4,Aberdeen City,138,8,8,0,16,0.5
1,2019,4,Aberdeenshire,77,0,0,1,1,0.0
2,2019,4,Angus,42,0,0,0,0,0.0
3,2019,4,Argyll and Bute,65,0,1,0,1,0.0
4,2019,4,Clackmannanshire,37,0,0,0,0,0.0

In [6]:
df.head(-10)

,year,month,source_location,DETECTED CRIME,negative,neutral,positive,total,neg_ratio
0,2019,4,Aberdeen City,138,8,8,0,16,0.500000
1,2019,4,Aberdeenshire,77,0,0,1,1,0.000000
2,2019,4,Angus,42,0,0,0,0,0.000000
3,2019,4,Argyll and Bute,65,0,1,0,1,0.000000
4,2019,4,Clackmannanshire,37,0,0,0,0,0.000000
...,...,...,...,...,...,...,...,...,...
2191,2024,12,Midlothian,26,0,0,0,0,0.000000
2192,2024,12,Moray,32,0,0,1,1,0.000000
2193,2024,12,North Ayrshire,92,0,1,0,1,0.000000
2194,2024,12,North Lanarkshire,228,4,3,0,7,0.571429
2195,2024,12,Orkney Islands,5,0,0,1,1,0.000000

In [8]:
import pandas as pd
import numpy as np
from calendar import monthrange

# Example: your original dataframe
# df = pd.DataFrame({
#     'year': [2023, 2023],
#     'month': [1, 1],
#     'source_location': ['A', 'B'],
#     'detected_crime': [93, 120]
# })

# Create an empty list to store the rows of the new dataframe
rows = []

# Iterate through each row in the original df
for _, row in df.iterrows():
    year = row['year']
    month = row['month']
    source = row['source_location']
    total_crime = row['DETECTED CRIME']
    negative = row['negative']
    neutral = row['neutral']
    positive = row['positive']
    total = row['total']
    neg_ratio = row['neg_ratio']
    
    # Get number of days in the month
    num_days = monthrange(year, month)[1]
    
    # Random distribution base: start with equal distribution
    base = total_crime // num_days
    crimes = [base] * num_days

    # Distribute the remainder randomly with small adjustments
    remainder = total_crime - sum(crimes)
    for _ in range(remainder):
        index = np.random.randint(0, num_days)
        crimes[index] += 1

    # Optionally, add small noise to the base (not affecting sum)
    noise = np.random.randint(-1, 2, size=num_days)
    crimes = np.array(crimes) + noise

    # Ensure no value goes below 0
    crimes = np.maximum(crimes, 0)

    # Calculate the difference after noise
    total_after_noise = crimes.sum()
    diff = total_crime - total_after_noise

    # If there is a difference, adjust to balance the total
    if diff != 0:
        adjust_indices = np.random.choice(num_days, abs(diff), replace=True)
        for idx in adjust_indices:
            crimes[idx] += 1 if diff > 0 else -1

    # Ensure no value goes below 0 after adjustment
    crimes = np.maximum(crimes, 0)

    # Recalculate the total after adjustment to ensure it equals the original total
    total_after_adjustment = crimes.sum()

    # If the sum is still not equal to total_crime, adjust the last crime entry
    if total_after_adjustment != total_crime:
        diff = total_crime - total_after_adjustment
        crimes[-1] += diff

    # Append to rows
    for day, daily_crime in enumerate(crimes, 1):
        rows.append({
            'year': year,
            'month': month,
            'day': day,
            'source_location': source,
            'DETECTED CRIME': daily_crime,
            'negative': negative,
            'neutral': neutral,
            'positive': positive,
            'total': total,
            'neg_ratio': neg_ratio
        })

# Create the new dataframe
ndf = pd.DataFrame(rows)

In [9]:
ndf.shape

(67203, 10)

In [10]:
ndf.head(40)

,year,month,day,source_location,DETECTED CRIME,negative,neutral,positive,total,neg_ratio
0,2019,4,1,Aberdeen City,4,8,8,0,16,0.5
1,2019,4,2,Aberdeen City,4,8,8,0,16,0.5
2,2019,4,3,Aberdeen City,4,8,8,0,16,0.5
3,2019,4,4,Aberdeen City,6,8,8,0,16,0.5
4,2019,4,5,Aberdeen City,3,8,8,0,16,0.5
5,2019,4,6,Aberdeen City,5,8,8,0,16,0.5
6,2019,4,7,Aberdeen City,6,8,8,0,16,0.5
7,2019,4,8,Aberdeen City,3,8,8,0,16,0.5
8,2019,4,9,Aberdeen City,5,8,8,0,16,0.5
9,2019,4,10,Aberdeen City,5,8,8,0,16,0.5
10,2019,4,11,Aberdeen City,7,8,8,0,16,0.5
11,2019,4,12,Aberdeen City,6,8,8,0,16,0.5
12,2019,4,13,Aberdeen City,3,8,8,0,16,0.5
13,2019,4,14,Aberdeen City,4,8,8,0,16,0.5
14,2019,4,15,Aberdeen City,4,8,8,0,16,0.5
15,2019,4,16,Aberdeen City,7,8,8,0,16,0.5
16,2019,4,17,Aberdeen City,4,8,8,0,16,0.5
17,2019,4,18,Aberdeen City,5,8,8,0,16,0.5
18,2019,4,19,Aberdeen City,5,8,8,0,16,0.5
19,2019,4,20,Aberdeen City,4,8,8,0,16,0.5
20,2019,4,21,Aberdeen City,4,8,8,0,16,0.5
21,2019,4,22,Aberdeen City,5,8,8,0,16,0.5
22,2019,4,23,Aberdeen City,5,8,8,0,16,0.5
23,2019,4,24,Aberdeen City,3,8,8,0,16,0.5
24,2019,4,25,Aberdeen City,3,8,8,0,16,0.5
25,2019,4,26,Aberdeen City,5,8,8,0,16,0.5
26,2019,4,27,Aberdeen City,6,8,8,0,16,0.5
27,2019,4,28,Aberdeen City,4,8,8,0,16,0.5
28,2019,4,29,Aberdeen City,4,8,8,0,16,0.5
29,2019,4,30,Aberdeen City,5,8,8,0,16,0.5
30,2019,4,1,Aberdeenshire,3,0,0,1,1,0.0
31,2019,4,2,Aberdeenshire,2,0,0,1,1,0.0
32,2019,4,3,Aberdeenshire,1,0,0,1,1,0.0
33,2019,4,4,Aberdeenshire,3,0,0,1,1,0.0
34,2019,4,5,Aberdeenshire,2,0,0,1,1,0.0
35,2019,4,6,Aberdeenshire,1,0,0,1,1,0.0
36,2019,4,7,Aberdeenshire,4,0,0,1,1,0.0
37,2019,4,8,Aberdeenshire,3,0,0,1,1,0.0
38,2019,4,9,Aberdeenshire,3,0,0,1,1,0.0
39,2019,4,10,Aberdeenshire,2,0,0,1,1,0.0

In [12]:
json_output = ndf.to_json(orient='records')
with open('daywise_crime.json', 'w') as f:
    f.write(json_output)

In [11]:
ndf.to_csv('daywise_crime.csv', index=False)